---
- name: 'Cleanup VMs'
  hosts: proxmox 
  vars_files:
    - ../vars/okd.yml
  tasks:
  - name: 'Stop all VMS' 
    proxmox_kvm:
      vmid: '{{  vmidprefix }}{{ item.vmid | default([])}}'
      api_user: "{{ pve.api_user }}"
      api_password: "{{ pve.api_password }}"
      api_host: "{{ pve.api_host }}"
      node: '{{ item.node | default(defaults.node) }}'
      state       : stopped
      force: yes
    with_items: "{{ nodes }}"
    ignore_errors: yes
    tags: stop
  - name: 'Remove all VMS if old ones are there' 
    proxmox_kvm:
      vmid: '{{  vmidprefix }}{{ item.vmid | default([])}}'
      api_user: "{{ pve.api_user }}"
      api_password: "{{ pve.api_password }}"
      api_host: "{{ pve.api_host }}"
      node: '{{ item.node | default(defaults.node) }}'
      state       : absent
    with_items: "{{ nodes }}"
    tags: delete 
    ignore_errors: yes
