---
# handlers file for tester
- name: restart haproxy
  service:
    name: haproxy
    state: restarted

- name: restart tftp
  service:
    name: tftp
    state: restarted

- name: restart httpd
  service:
    name: httpd
    state: restarted
